app_name : MobileInsight

app_version : 2.0

pkg_name : edu.ucla.cs.wing.mobileinsight

dist_name : mi2

bootstrap : pygame

requirements : kivy,mobileinsight

# replace it with your path of python-for-android
p4a_path : /Users/Dale/.python-for-android/

# replace it with your application icon path
icon_path : /Users/Dale/Workspace/mobileInsight/MobileInsight2/icon.png

# replace it with your application presplash path
presplash_path : /Users/Dale/Workspace/mobileInsight/MobileInsight2/presplash.jpg

# replace it with your applicaiton path
app_path : /Users/Dale/Workspace/mobileInsight/MobileInsight2/demo_app

# replace it with your path of Android SDK
sdk_path : /Users/Dale/Library/Android/sdk

# replace it with your Android NDK path
ndk_path : /Users/Dale/Library/Android/android-ndk-r10e

# replace it with your desired target arch
arch : armeabi

# replace it with your Android SDK version (compiling Android API level)
sdk_version : 19

# replace it with your target Android API level
api_level : 19

# replace it with your minimal Android API level
minsdk : 14

# replace it with your Android NDK version
ndk_version : r10e

orientation : portrait

whitelist : whitelist.txt

keystore : /Users/zyuan/Projects/metro/mi2-release-key.keystore
signkey : mi2-key
keystorepw : keystore-password
signkeypw : key-password
